packages:
  - tree-sitter-zsh

configDependencies:
  '@pnpm/plugin-types-fixer': 0.1.0+sha512-bLww63gRHi7siYTqFJb5qNdcXadU0jv20Et6z5AryMZ7FlLolbEJOrXLpg8+amQZNHHNW1dfFUBGVw/9ezQbFg==

onlyBuiltDependencies:
  - tree-sitter
  - tree-sitter-cli

updateNotifier: false
autoInstallPeers: true
nodeLinker: hoisted
